# Generated by Django 3.1.6 on 2021-02-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20210204_1923'),
        ('books', '0002_auto_20210216_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='references.BookAuthor', verbose_name="Book's author"),
        ),
    ]
