# Generated by Django 3.1.6 on 2021-02-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='count of items')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated date time')),
                ('item_in_basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item in basket +', to='books.book', verbose_name='wich item is in the basket')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated date time')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basket', to='baskets.iteminbasket', verbose_name='items')),
            ],
        ),
    ]
