# Generated by Django 3.1.6 on 2021-02-04 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 16, 17, 55, 303021, tzinfo=utc), verbose_name='created date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date time'),
        ),
    ]
