# Generated by Django 3.1.6 on 2021-02-04 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20210204_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 16, 22, 56, 855236, tzinfo=utc), verbose_name='created date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date time'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 16, 23, 15, 863141, tzinfo=utc), verbose_name='created date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date time'),
        ),
        migrations.AddField(
            model_name='series',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 16, 23, 20, 446916, tzinfo=utc), verbose_name='created date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date time'),
        ),
    ]
